services:
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.57
    ports:
      - 16686:16686 # UI
      - 6831:6831/udp # Traces UDP
      - 14268:14268 # Traces HTTP
      - 4317:4317 # OTLP/gRPC
      - 4318:4318 # OTLP/HTTP

  postgres:
    container_name: postgres
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blink

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672 # Server
      - 15672:15672 # UI

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
